Repository replicatedhq/embedded-cluster-kinds, pull requests merged in 2024-07, with the labels that each got.

#46 Reimpliment chart types from k0s/v1beta1
  apis/v1beta1/config_types.go
  apis/v1beta1/zz_generated.deepcopy.go
  types/release_metadata.go
Labels: type::chore

#54 use pointer for json unmarshal
  apis/v1beta1/config_types.go
  apis/v1beta1/config_types_test.go
Labels: bug::normal, type::bug

#55 just pass in the pointer
  apis/v1beta1/config_types.go
  apis/v1beta1/config_types_test.go
Labels: type::chore

#56 do not use generic types for ConvertTo and ConvertFrom as the k0s type will always have the same import
  apis/v1beta1/config_types.go
Labels: type::chore

#59 feat: add ReleaseMetadata.Images field to keep track of all images in release
  types/release_metadata.go
Labels: type::feature
