Repository replicatedhq/embedded-cluster-kinds, pull requests merged in 2024-05, with the labels that each got.

#18 allow including the list of pending charts in the installation status
  apis/v1beta1/installation_types.go
  apis/v1beta1/zz_generated.deepcopy.go
Labels: type::feature

#19 update the setstate function to include pending charts
  apis/v1beta1/installation_types.go
Labels: type::feature

#22 chore: add a missing unit test
  apis/v1beta1/testdata/config-override-with-unknown-fields.yaml
Labels: type::chore

#24 feat: return error if secret does not contain config entry
  apis/v1beta1/installation_types.go
  apis/v1beta1/installation_types_test.go
  apis/v1beta1/testdata/config-override-no-entry.yaml
Labels: type::feature

#27 return k0s import to 1.28.x
  go.mod
  go.sum
Labels: type::chore

#30 DR license field
  apis/v1beta1/installation_types.go
Labels: type::feature

#31 omitempty for DR field
  apis/v1beta1/installation_types.go
Labels: type::feature

#33 import github.com/k0sproject/k0s@v1.28.8+k0s.0 to allow for upgrade testing
  go.mod
  go.sum
Labels: type::chore

#34 add isHighAvailability field to installation spec
  apis/v1beta1/installation_types.go
Labels: type::feature

#35 omitempty installation spec fields
  apis/v1beta1/installation_types.go
Labels: bug::normal, type::bug

#37 rename high availability field in installation spec
  apis/v1beta1/installation_types.go
Labels: type::feature

#38 check if generated files are up to date in PRs
  .github/workflows/pull-request.yaml
Labels: type::chore

#36 feat: add support for ha registry
  apis/v1beta1/installation_types.go
  apis/v1beta1/zz_generated.deepcopy.go
Labels: type::feature

#39 chore: remove deprecated ReleaseMetadata.AirgapConfigs
  types/release_metadata.go
Labels: type::chore
